### ISSUE TITLE
Constraints - Disturbances are sometimes not well ordered in time

### ISSUE THREAD

**Issue by pedrogit** [CASFRI/CASFRI#408]
According to the specifications "Up to three disturbance events can be recorded with the oldest event described first." But sometimes DIST_YEAR_2 is smaller than DIST_YEAR_1 or DIST_YEAR_3 is smaller than DIST_YEAR_2.

This is now checked by constraint 2.22, 2.23 and 2.24.

**Comment by pedrogit** [comment]
@edwardsmarc Was something done to fix this?

**Comment by edwardsmarc** [comment]
I fixed it in AB in #544

I don't think it happens elsewhere, but we should check by running the constraints

**Comment by pedrogit** [comment]
This is now checked by constraint 2.25 and 2.26 and they both fail.

**Comment by edwardsmarc** [comment]
Can yo provide more details? When I run the following queries I get zero rows returned, which suggests disturbances are correctly orgdered:

```
SELECT * FROM casfri50.dst_all
WHERE dist_year_2 > 0 AND dist_year_1 > dist_year_2 LIMIT 1000

SELECT * FROM casfri50.dst_all
WHERE dist_year_3 > 0 AND dist_year_2 > dist_year_3 LIMIT 1000
```

**Comment by pedrogit** [comment]
This happens in my last complete translation in SK04, SK06, SK02, SK05. Running the same queries you provided returns many rows. If I look at everything that was commited after I pulled the code for that complete translation, it does not seems to have been fixed. I suggest you just retranslate SK02 and check, it's the smallest one of the four and with the new engine, it should be quite fast.

**Comment by edwardsmarc** [comment]
New functions needed to order SK disturbances. Currently we use minIndex and maxIndex family of functions but SK has 3 disturbances so we need to be able to pass the requested index to the function.

**Comment by edwardsmarc** [comment]
https://github.com/edwardsmarc/PostgreSQL-Table-Translation-Framework/issues/244

**Comment by edwardsmarc** [comment]
Have started solving this with TT_getIndexTestVal().

Now need the other functions to call this and pass the value to notNull, isInt etc.

**Comment by edwardsmarc** [comment]
Fixed for SK.

Constraints should be checked before closing.

**Comment by pedrogit** [comment]
Still not passing in 5.3.0

**Comment by edwardsmarc** [comment]
Not passing because of value -9998 in SK06, MB02, MB04 and MB06. Fixed by setting error code to -8888 when catching zero values.

Constraints need to be re-checked.
