### ISSUE TITLE
AB can have NFL spread across multiple columns

### ISSUE THREAD

**Issue by edwardsmarc** [CASFRI/CASFRI#526]
There is an NFL type in AB AVI that indicates **rough pasture**. Every time this is reported, the AVI requires an **open shrub** or **closed shrub** record to go with it indicating the height and extent of shrub cover in the rough pasture.

Rough pasture is reported in CASFRI as the NON_FOR_ANTH value: CULTIVATED.

Rough pasture always has the shrub component which gets reported in CASFRI as NON_FOR_VEG value LOW_SHRUB or TALL_SHRUB, with associated height and extent cover.

So the polygons in this case are rough pastures that have x% cover of shrubs.

**Question 1: should we report both CULTIVATED and TALL_SHRUB/LOW_SHRUB?**

**Question 2: if we report both, should they be in the same layer or different layers? Usually we avoid having two NFL attributes reporting values in the same CASFRI row (see #365).**

My preference is to report both in the same CASFRI NFL row. i.e. we consider them to be a single layer since they always occur together and are defined as such in the manual. This matches the source data where both attributes are included in the same row.

This would be the first example where we deliberately have 2 NFL types reported in the same row. BC and SK have multiple NFL types per polygon but we report them in separate rows/layers because they came from distinct parts of the source dataset (e.g. SK SFVI has a shrub table, and herb table, and an nfl table).

**Comment by edwardsmarc** [comment]
Note that currently the translation is set up to report both attributes in the same row.
To report them in different rows would require adding additional NFL rows to attribute_dependencies and adding AB functions to hasNFLInfo().

**Comment by pedrogit** [comment]
By reporting them on the same row you would be in contradiction with what was agreed in #365. The fact that both occurs always at the same time and come from the same row in the source should not influence the way we structured CASFRI and the rules we agreed upon. In the new schema they would definitely be in two diffrent rows whatever the source says.

**Comment by edwardsmarc** [comment]
OK I'll translate them on different rows. Do we have a constraint that checks for this using your query above?

**Comment by pedrogit** [comment]
No. Good point. Don't close the issue until we have added the constraint.

**Comment by edwardsmarc** [comment]
Update:

Many of the rows where this exists have horizontal structure with an associated structure percent. This indicates that the pasture/shrub mix takes up say 75% of the polygon. If we split pasture and shrub into 2 CASFRI layers both will be assigned a structure percent of 75% which is clearly incorrect. They should remain part of the same horizontal sub-component.

The only solution I see is to either violate #365, or simply remove either the pasture or shrub designations.

**Comment by pedrogit** [comment]
Let's make an exception for horizontal structures then.

**Comment by edwardsmarc** [comment]
OK, the exception will have to be for the whole inventories where this occurs: AB03, AB25 and AB29.

Reason is that the pasture/shrub combo can occur as a horizontal component or as a vertical component in these inventories. If we wanted to split pasture and shrub into different layers we would do that via the attribute_dependencies tables and the workflow. We would run NAT_NON_VEG, NON_FOR_ANTH and NON_FOR_VEG as three different translations that would create potentially three different layers.

There is no way to split the layers for vertical polygons, and leave them together for horizontal. Because the layer assignment is done at the attribute_dependencies/workflow level, and the identification of horizontal structure is done at the level of the translation table.

**Comment by edwardsmarc** [comment]
We should still add the constraint, but do not apply it to AB03, AB25, or AB29

**Comment by edwardsmarc** [comment]
This issue is complicated by the fact that in addition to the SHRUB x CULTIVATED combination that we have deemed to be acceptable, there are also other instances where two NFL values occur on the same row (note this happens on 13 rows across all 4 inventories). This happens in AB03, AB10, AB25 and AB29. All cases can be seen using this query:

```
SELECT LEFT(nfl.cas_id,4) x, nfl.nat_non_veg, nfl.non_for_veg, nfl.non_for_anth, count(*)
FROM casfri50.nfl_all AS nfl
  LEFT JOIN casfri50.cas_all AS cas
  ON nfl.cas_id = cas.cas_id
WHERE ((non_for_veg=ANY(TT_IsMissingOrNotInSetCode()))::int + (nat_non_veg=ANY(TT_IsMissingOrNotInSetCode()))::int + (non_for_anth=ANY(TT_IsMissingOrNotInSetCode()))::int)!=2
GROUP BY x, nfl.nat_non_veg, nfl.non_for_veg, nfl.non_for_anth
```

Ideally we would split these into multiple layers in the case of vertical stands, and leave them on the same row for horizontal stands. But that is not possible using the workflow for the reasons stated above (but see option 3 below).

So our options are:
1. Leave them in and accept that these 4 datasets will violate the standard and have rows with multiple NFL values.
2. Catch the cases that are not the accepted SHRUB x CULTIVATED and return an error code. This could be done with a custom validation function.
3. Technically we could adapt the workflow to accommodate this by adding a stand structure flag and running the translation table once for the horizontal rows, and twice for the vertical rows. When running a horizontal row we allow multiple NFL attributes per row. When running a vertical row we would split them up. We would also allow the SHRUB x CULTIVATED case to be returned in vertical stands.

Given that this only effect 13 rows, I propose we use option 1.

**Comment by edwardsmarc** [comment]
This is an updated query to see the rows in question:

```
SELECT LEFT(nfl.cas_id,4) x, nfl.nat_non_veg, nfl.non_for_veg, nfl.non_for_anth, cas.stand_structure, count(*)
FROM casfri50.nfl_all AS nfl
  LEFT JOIN casfri50.cas_all AS cas
  ON nfl.cas_id = cas.cas_id
WHERE ((nfl.non_for_veg=ANY(TT_IsMissingOrNotInSetCode()))::int + (nfl.nat_non_veg=ANY(TT_IsMissingOrNotInSetCode()))::int + (nfl.non_for_anth=ANY(TT_IsMissingOrNotInSetCode()))::int)!=2 
  AND LEFT(nfl.cas_id,4) IN('AB03', 'AB10', 'AB25', 'AB29')
GROUP BY x, nfl.nat_non_veg, nfl.non_for_veg, nfl.non_for_anth, cas.stand_structure
```

The decision for now is to leave these all in the same rows and document the decision in the NFL translation table.

**Comment by pedrogit** [comment]
NB01, YT02, SK03, AB16 and NS03 do not fullfil the new constraint (now 5.27). To find the rows not fullfilling the constraint:

```
SELECT DISTINCT left(cas_id, 4) inv
FROM casfri50.nfl_all
WHERE NOT (left(cas_id, 4) IN('AB03', 'AB25', 'AB29', 'AB10') OR
							  (
							  ((non_for_veg=ANY(TT_IsMissingOrNotInSetCode()))::int + 
                 (nat_non_veg=ANY(TT_IsMissingOrNotInSetCode()))::int + 
                 (non_for_anth=ANY(TT_IsMissingOrNotInSetCode()))::int)=2
							  ))

```

**Comment by edwardsmarc** [comment]
AB16 has 5 rows where LOW_SHRUB and FACILITY_INFRASTRUSTURE and on the same row. We can't separate these for the same reason described earlier in this issue for AB.

So AB16 should be added as an exception in the constraint.

All the other inventories listed don't have multiple values per row, at least based on my queries on the source data. I think they might have error codes that don't match TT_IsMissingOrNotInSetCode() but I can't check without running the full translation.

**Comment by edwardsmarc** [comment]
The 433 rows in MB05 are caused by code 840 which is not listed in the manual. We catch these as UNKNOWN_VALUES. We know it's an NFL class but don't know the meaning. We could just drop if from ROW_TRANSLATION_RULE.

Same for SK03, caused by 3 UNKNOWN_VALUE entries.

**Comment by pedrogit** [comment]
I don't think we should drop rows when they contain invalid info for NFL or LYR. We should just translate them to their appropriate error code.

**Comment by edwardsmarc** [comment]
OK, that's what's currently happening but it causes the constraint to fail. So we need to make the case where NFL attributes are e.g. NOT_APPLICABLE, NOT_APPLICABLE, UNKNOWN_VALUE to be accepted by the constraints.
