### ISSUE TITLE
Constraints - Four NS01 and NS02 rows produce CAS_ID = 'NULL'

### ISSUE THREAD

**Issue by pedrogit** [CASFRI/CASFRI#623]
There must be a link between those and the ones in #622

**Comment by edwardsmarc** [comment]
This is caused by 2 null mapsheet values. I'll fix it by removing the notNull validation rule.

**Comment by edwardsmarc** [comment]
Constraints still fail.

The problem here is that TT_PadConcat returns NULL if any of the input source values are NULL.

Fix is listed in engine issue: https://github.com/edwardsmarc/PostgreSQL-Table-Translation-Framework/issues/248

**Comment by pedrogit** [comment]
What will happen when the engine fix is applied?

**Comment by edwardsmarc** [comment]
The CAS_ID will include all pad characters for map_sheet_id in these cases: 'xxxxxxxxxx'

**Comment by edwardsmarc** [comment]
Should be fixed. Check constraint before closing

**Comment by pedrogit** [comment]
Forgot to close when committing. Closing...
