### ISSUE TITLE
Constraints - DIST_EXT_LOWER_1 and UPPER_1 uses wrong error code for AB16

### ISSUE THREAD

**Issue by prvernier** [CASFRI/CASFRI#666]
DIST_EXT_LOWER_1 and DIS_EXT_UPPER_1 have one instance of using an invalid error code: -9995 (WRONG_TYPE) for AB16.

**Comment by pedrogit** [comment]
Fixed and only remains to check the constraints?

**Comment by edwardsmarc** [comment]
Yes.

**Comment by pedrogit** [comment]
Constraints passing in release 5.3.1. Closing...
