### ISSUE TITLE
Constraints - PE01 DST translate one DIST_TYPE_1 to INVALID_VALUE

### ISSUE THREAD

**Issue by pedrogit** [CASFRI/CASFRI#696]
It should be NOT_IN_SET for codes.

"PE01-1990_FORESTINVE-xxxxxxxx44-xxxxx47691-xx26051"

**Comment by edwardsmarc** [comment]
DST codes are 2 characters long. Up to 2 disturbances are possible, coded in a single string. Valid code lengths are therefore 2 and 4.

The code in this case only has 1 character and is therefore invalid. That's why I used INVALID_VALUE. Do you still think it should be changed to NOT_IN_SET.

**Comment by pedrogit** [comment]
I'll had INVALID_VALUE as an acceptable values for code attributes.
