### ISSUE TITLE
Constraints - SK06 DST translate some DIST_YEAR_1 as -9998 (NOT_IN_SET)

### ISSUE THREAD

**Issue by pedrogit** [CASFRI/CASFRI#697]
DIST_YEAR_1 is a range of values. When out of range the error should be -9999

The error code must be set according to the type of the target attribue. Not the type of the source attribute.

**Comment by edwardsmarc** [comment]
Should have already been fixed with cc6ffd26577fa144a6ed60933f681c389869b91d

Check constraints before closing
