### ISSUE TITLE
Constraints - Translation of NON_FOR_VEG for YT01 generates some TRANSLATION_ERROR

### ISSUE THREAD

**Issue by pedrogit** [CASFRI/CASFRI#704]
"YT01-INVENTORY_POLY_-xxxxxxxxxx-xxxxxxxx94-xxxx416"
"YT01-INVENTORY_POLY_-xxxxxxxxxx-xxxxxxx316-xx11371"
"YT01-INVENTORY_POLY_-xxxxxxxxxx-xxxxxxxxx0-x117943"
"YT01-INVENTORY_POLY_-xxxxxxxxxx-xxxxxxxx90-x195424"

**Comment by edwardsmarc** [comment]
Fixed, check constraints
