### ISSUE TITLE
QC05 loading script fails when launched from load_all.sh

### ISSUE THREAD

**Issue by edwardsmarc** [CASFRI/CASFRI#712]
KA gets the following error when loading qc05 from load_all.sh after changing shell path to `bashCmd="/bin/bash"`

```
ERROR 1: Unable to write feature 1 from layer PEE_MAJ_PROV.
ERROR 1: Terminating translation prematurely after failed
translation from sql statement.
```

It loads fine when the script is launched directly.

**Comment by pedrogit** [comment]
I tested again and I could load all three QC01, QC04 and QC05 inventories in parallel by setting them in the config.sh invList1 variable and by launching load_all.sh

That's on Windows using GDAL 3.4.1.

The problem might be du to the GDAL version (even the same version number) on Linux.

**Comment by pedrogit** [comment]
Worked fine in the last release. Lowering priority to medium.
