### ISSUE TITLE
Constraints - Some NS, NT and YT LAYER attributes are assigned a wrong value

### ISSUE THREAD

**Issue by pedrogit** [CASFRI/CASFRI#723]
WITH all_layers_numbers AS (
  SELECT cas_id, 'lyr' || layer::text layer  FROM casfri50.lyr_all
  UNION ALL
  SELECT cas_id, 'nfl' || layer::text layer  FROM casfri50.nfl_all
), all_layers_orders AS (
  SELECT cas_id, string_agg(layer::text, '_' ORDER BY layer) layers_order
  FROM all_layers_numbers
  GROUP BY cas_id
)
SELECT cas_id, layers_order
FROM all_layers_orders
WHERE layers_order != 'lyr1' AND
      layers_order != 'lyr1_lyr2' AND
      layers_order != 'lyr1_lyr2_lyr3' AND
      layers_order != 'lyr1_lyr2_lyr3_lyr4' AND
      layers_order != 'lyr1_lyr2_lyr3_lyr4_lyr5' AND
      layers_order != 'lyr1_lyr2_lyr3_lyr4_nfl5' AND
      layers_order != 'lyr1_lyr2_lyr3_lyr4_nfl5_nfl6' AND
      layers_order != 'lyr1_lyr2_lyr3_lyr4_nfl5_nfl6_nfl7' AND
      layers_order != 'lyr1_lyr2_lyr3_nfl4' AND
      layers_order != 'lyr1_lyr2_lyr3_nfl4_nfl5' AND
      layers_order != 'lyr1_lyr2_lyr3_nfl4_nfl5_nfl6' AND
      layers_order != 'lyr1_lyr2_lyr3_nfl4_nfl5_nfl6_nfl7' AND
      layers_order != 'lyr1_lyr2_nfl3' AND
      layers_order != 'lyr1_lyr2_nfl3_nfl4' AND
      layers_order != 'lyr1_lyr2_nfl3_nfl4_nfl5' AND
      layers_order != 'lyr1_lyr2_nfl3_nfl4_nfl5_nfl6' AND
      layers_order != 'lyr1_nfl2' AND
      layers_order != 'lyr1_nfl2_nfl3' AND
      layers_order != 'lyr1_nfl2_nfl3_nfl4' AND
      layers_order != 'lyr1_nfl2_nfl3_nfl4_nfl5' AND
      layers_order != 'nfl1' AND
      layers_order != 'nfl1_nfl2' AND
      layers_order != 'nfl1_nfl2_nfl3' AND
      layers_order != 'nfl1_nfl2_nfl3_nfl4';

Shows that:

- many NS01, NS02 and NS03 NFL rows get LAYER=0
- three NT03 NFL rows get LAYER=2 when 2 is already assigned to the LAYER attribute of the corresponding LYR rows
- one YT01 NFL row get LAYER=1 when 1 is already assigned to the LAYER attribute of the corresponding LYR row

This is checked by the upcoming new version of 03_addConstraints.sql (see #713)

**Comment by edwardsmarc** [comment]
YT left to fix

**Comment by edwardsmarc** [comment]
Should all be fixed, check constraints.

**Comment by pedrogit** [comment]
Replaced by two different issues:

#739 Some NUMBER_OF_LAYERS values do not match the actual number of NFL and LYR layers

and 

#740 Many NB02 and ON01 NFL rows have LAYER = 0

Closing.
