### ISSUE TITLE
Some CAS NT03 rows (123) have STAND_STRUCTURE = 'MULTI_LAYERED' and NUM_OF_LAYERS=1

### ISSUE THREAD

**Issue by pedrogit** [CASFRI/CASFRI#736]
This makes constraint 1.17 to fail

**Comment by edwardsmarc** [comment]
Error in TT_row_translation_rule_nt_lyr().
`IF typeclas IN('TC', 'TB', 'TM')` should be changed to `IF typeclas NOT IN(all nfl values)`

In fvi01_countofnotnull remove:
```
-- if overstory is forest type assign species, otherwise set to null
	IF typeclas = ANY(lyr_string_list) THEN
	  _lyr1 = vals1;
	ELSE
	  _lyr1 = NULL::text;
	END IF;

	-- if understory is forest type assign species, otherwise set to null
	IF mintypeclas = ANY(lyr_string_list) THEN
	  _lyr2 = vals2;
	ELSE
	  _lyr2 = NULL::text;
	END IF;
```
Just count a layer if species are present. Doesn't matter if typeclas is included.

**Comment by edwardsmarc** [comment]
I'm expecting an increase in LYR rows. And the error rows should be fixed. They will still be MULTI_LAYERED but should have counts of 2.

**Comment by edwardsmarc** [comment]
Fix attempted, PR to check
