### ISSUE TITLE
Many NB02 and ON01 NFL rows have LAYER = 0

### ISSUE THREAD

**Issue by pedrogit** [CASFRI/CASFRI#740]
1325 rows in ON01 and 1770 in NB02. 

At some point the constraints were adjusted to allow NFL LAYER=0 but the spec says nothing about it.

If it is allowed then constraint 1.4 in 03_additionalChecks.sql should be adjusted to allow 'nfl0'.

If it is not then constraint 5.16 from 01_addConstraints.sql should be changed to not allow LAYER=0

**Comment by pedrogit** [comment]
According to Marc no NFL LAYER value should be  = 0. So changing constraint 5.16 and keeping the issue open.

**Comment by edwardsmarc** [comment]
This should have been fixed by fixing #739.

**Comment by pedrogit** [comment]
Now we get a LAYER = -3333 for those CAS_IDS:

NT01-NT_FORCOV_UPDAT-xxxxxxxxx8-xxx8002201-xx15663
NT01-NT_FORCOV_UPDAT-xxxxxxxxx8-xxx8005724-xx20943
NT01-NT_FORCOV_UPDAT-xxxxxxxxx8-xxx8005821-xx21000
NT03-xxxxxNT_FORCOV_-xxxxxxxxx8-xxx8005724-xx73378
NT03-xxxxxNT_FORCOV_-xxxxxxxxx8-xxx8005821-xx73355
NT03-xxxxxNT_FORCOV_-xxxxxxxxx8-xxx8002201-xx56722
